version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
    - /home/code/db:/code/
    depends_on:
      - db
    command: ./start.sh

  db:
    image: postgres
    restart: always
    volumes:
      - /db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

